# Generated by Django 4.0 on 2022-02-23 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(blank=True, max_length=200, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('workExperience', models.CharField(blank=True, default='Белгиланмаган', max_length=100, null=True)),
                ('personalSkills', models.CharField(blank=True, default='Белгиланмаган', max_length=150, null=True)),
                ('languages', models.CharField(blank=True, default='Белгиланмаган', max_length=100, null=True)),
                ('Place', models.CharField(blank=True, default='Белгиланмаган', max_length=200, null=True)),
                ('jobText', models.TextField()),
                ('JobDate', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['JobDate'],
            },
        ),
        migrations.CreateModel(
            name='UserForm_uz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='media/rasmlar')),
                ('lastName', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=200)),
                ('middleName', models.CharField(blank=True, max_length=200, null=True)),
                ('birthData', models.DateField()),
                ('nation', models.CharField(blank=True, max_length=50, null=True)),
                ('birthPlace', models.CharField(max_length=250)),
                ('additionalCourses', models.CharField(blank=True, max_length=300, null=True)),
                ('language_uzbek', models.CharField(max_length=150)),
                ('language_russian', models.CharField(max_length=150)),
                ('language_english', models.CharField(blank=True, max_length=150, null=True)),
                ('language_boshqa', models.CharField(blank=True, max_length=50, null=True)),
                ('computer_literacy', models.CharField(max_length=15)),
                ('homeNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('jobName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forma_app.job')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewDay', models.CharField(max_length=50)),
                ('InterviewTime', models.PositiveSmallIntegerField()),
                ('interviewJob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forma_app.job')),
            ],
        ),
        migrations.CreateModel(
            name='Experience_uz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startWorkDate', models.DateField(blank=True, null=True)),
                ('endWorkDate', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('lavozim', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forma_app.userform_uz')),
            ],
        ),
        migrations.CreateModel(
            name='Education_uz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startingDate', models.DateField()),
                ('endingDate', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=50)),
                ('speciality', models.CharField(max_length=150)),
                ('diplomSeriya', models.CharField(max_length=50)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forma_app.userform_uz')),
            ],
        ),
    ]
