# Generated by Django 3.2.9 on 2021-11-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forma_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='languages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='personalSkills',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='workExperience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
