# Generated by Django 4.0 on 2022-02-23 09:24

from django.db import migrations, models
import forma_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('forma_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform_uz',
            name='test_id',
            field=models.CharField(default=forma_app.models.random_string, max_length=5),
        ),
    ]
