# Generated by Django 3.2.9 on 2021-11-28 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forma_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience_uz',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experience_uz',
            name='endWorkDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience_uz',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forma_app.userform_uz'),
        ),
        migrations.AlterField(
            model_name='experience_uz',
            name='lavozim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experience_uz',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experience_uz',
            name='startWorkDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otherdocuments',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otherdocuments',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forma_app.userform_uz'),
        ),
        migrations.AlterField(
            model_name='recommendation_uz',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forma_app.userform_uz'),
        ),
        migrations.AlterField(
            model_name='recommendation_uz',
            name='fullName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation_uz',
            name='phoneAndEmail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation_uz',
            name='workPlace',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userform_uz',
            name='additional_info',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userform_uz',
            name='diplom_file',
            field=models.FileField(default='ldsjfkldsjfldsk', upload_to='media/fayllar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userform_uz',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userform_uz',
            name='expected_salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userform_uz',
            name='functional_resp',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userform_uz',
            name='homeNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userform_uz',
            name='language_english',
            field=models.CharField(blank=True, choices=[('1', 'Билмайман'), ('2', 'Ёмон'), ('3', 'Лугат ёрдамида'), ('4', 'Ўртача'), ('5', 'Яхши'), ('6', 'Жуда яхши')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userform_uz',
            name='leaving_work_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userform_uz',
            name='main_skills',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userform_uz',
            name='middleName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userform_uz',
            name='nation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userform_uz',
            name='reasontoWork',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userform_uz',
            name='work_experience',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userform_uz',
            name='yutuqlar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
