# Generated by Django 3.2.9 on 2021-11-24 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forma_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_uz',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forma_app.userform_uz'),
        ),
    ]
