# Generated by Django 3.2.9 on 2021-12-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forma_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewDay', models.DateField()),
                ('InterviewTime', models.TimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='userform_uz',
            options={'ordering': ['time']},
        ),
    ]
