# Generated by Django 3.2.9 on 2021-12-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forma_app', '0002_auto_20211202_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='InterviewTime',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interviewDay',
            field=models.CharField(max_length=50),
        ),
    ]
