# Generated by Django 3.2.9 on 2021-11-25 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forma_app', '0002_alter_education_uz_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform_uz',
            name='diplom_file',
        ),
        migrations.RemoveField(
            model_name='userform_uz',
            name='passport_file',
        ),
        migrations.RemoveField(
            model_name='userform_uz',
            name='rasm',
        ),
        migrations.RemoveField(
            model_name='userform_uz',
            name='trudovoyKnishka',
        ),
    ]
