# Generated by Django 3.2.9 on 2021-11-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forma_app', '0002_auto_20211128_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform_uz',
            name='additionalCourses',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
