# Generated by Django 3.2.9 on 2021-11-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forma_app', '0003_userform_uz_additionalcourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform_uz',
            name='language_uzbek',
            field=models.CharField(max_length=150),
        ),
    ]
