# Generated by Django 3.2.9 on 2021-12-04 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forma_app', '0003_auto_20211203_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interviewJob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forma_app.userform_uz'),
        ),
    ]
