# Generated by Django 3.2.9 on 2021-11-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forma_app', '0004_alter_userform_uz_language_uzbek'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform_uz',
            name='personalSkills',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userform_uz',
            name='language_english',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userform_uz',
            name='language_russian',
            field=models.CharField(max_length=150),
        ),
    ]
