# Generated by Django 3.2.9 on 2021-11-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forma_app', '0005_auto_20211128_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform_uz',
            name='hobby',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userform_uz',
            name='hobby_boshqa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userform_uz',
            name='readinessWork',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userform_uz',
            name='agreement',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userform_uz',
            name='approve_info',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userform_uz',
            name='personalSkills',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
