# Generated by Django 3.2.9 on 2021-12-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forma_app', '0006_job_jobtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='JobDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
